### ISSUE TITLE
Change open to line and column syntax

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditCLI#16]
Instead of 
```
codeedit-cli Example.swift -l 43 -c 10
```
can we instead do something like...
```
codeedit Example.swift:43:10
```

- Change `codeedit-cli` to `codeedit`
- instead of `-l` and `-c`, the filename line and column are separated by `:`

This seems to be standard and is the case with VS Codes CLI. See their [documentation](https://code.visualstudio.com/docs/editor/command-line#_opening-files-and-folders) on open for reference.

**Comment by lukepistrol** [comment]
regarding renaming `codeedit-cli` to `codeedit`:

I think we should leave it as `codeedit-cli`, so that it is clear what the binary does. When a user likes to use `codeedit` instead they can easily create an alias for that. Also it might bring confusion once we want to bring both CodeEdit and the CLI to homebrew. `codeedit-cli` is just more describing imo

**Comment by austincondiff** [comment]
Closing this issue. Creating a separate issue to address the name change. @lukepistrol feel free to re-comment there.
